In [1]:
import torch

# Load the tensor
indices = torch.load('indices.pt')



C:\Users\tharu\AppData\Local\Temp\ipykernel_10288\569774741.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  indices = torch.load('indices.pt')


In [ ]:
indices_np = indices.numpy()  # Convert PyTorch tensor to NumPy array



In [49]:
indices

array([100, 329, 122,  67, 288, 126, 128, 140, 460, 372])

In [19]:
import numpy as np
import reedsolo

# Initialize RS codec (4 redundant symbols per block, 2 correctable errors)
rs = reedsolo.RSCodec(4)  # Add 4 redundant symbols

# Example: Original indices
indices = np.random.randint(0, 512, size=(12288,), dtype=np.uint16)  # Simulated indices
indices_bytes = indices.tobytes()  # Convert to bytes for RS encoding

# Encode with RS
encoded_data = rs.encode(indices_bytes)  # Add redundancy

# Save to a binary file
with open('encoded_data.bin', 'wb') as f:
    f.write(encoded_data)

print("Data encoded and saved to encoded_data.bin")


Data encoded and saved to encoded_data.bin


In [20]:
indices

array([318, 495, 248, ..., 278, 120,  61], dtype=uint16)

In [35]:
# Load the binary file
with open('encoded_data.bin', 'rb') as f:
    received_data = f.read()

# Simulate noise (e.g., flip random bits)
def add_noise(data, num_errors):
    noisy_data = bytearray(data)
    for _ in range(num_errors):
        byte_index = np.random.randint(len(noisy_data))
        bit_index = np.random.randint(8)
        noisy_data[byte_index] ^= (1 << bit_index)  # Flip a random bit
    return bytes(noisy_data)

# Add noise to the data
noisy_data = add_noise(received_data, num_errors=30)  # Simulate 10 random bit errors




In [36]:
# Decode the noisy data
try:
    decoded_data = rs.decode(noisy_data)  # Correct errors
    if isinstance(decoded_data, tuple):  # Check if the result is a tuple
        decoded_data = decoded_data[0]  # Extract the actual decoded data
    decoded_indices = np.frombuffer(decoded_data, dtype=np.uint16)  # Convert back to integers
    print("Data decoded successfully!")
except reedsolo.ReedSolomonError as e:
    print(f"Error during decoding: {e}")


Data decoded successfully!


In [37]:
indices == decoded_indices

array([ True,  True,  True, ...,  True,  True,  True])

In [38]:
decoded_indices

array([318, 495, 248, ..., 278, 120,  61], dtype=uint16)

In [61]:
import numpy as np


# Example: Original indices
indices = np.random.randint(0, 512, size=(12288,), dtype=np.uint16)  # Simulated indices
indices_bytes = indices.tobytes()  # Convert to bytes for RS encoding

# Encode with RS
encoded_data = indices_bytes  # Add redundancy

# Save to a binary file
with open('encoded_data_original.bin', 'wb') as f:
    f.write(encoded_data)

print("Data encoded and saved to encoded_data.bin")


Data encoded and saved to encoded_data.bin


In [62]:
indices

array([241, 205, 230, ..., 507, 471,  54], dtype=uint16)

b'\xf1\x00\xcd\x00\xe6\x00\xa2\x01\x82\x00\xe9\x00C\x01\x12\x00n\x01w\x00\xa0\x00\x06\x00\x84\x01}\x00!\x01\xf3\x01\xbd\x01=\x010\x01\x15\x00)\x00\x89\x00s\x01\xf5\x01X\x00J\x00\x9b\x01L\x01~\x00\xfd\x00#\x00h\x00@\x00D\x00\xf9\x01L\x00\x17\x00\t\x01\x93\x00\x9c\x00\x00\x00\x96\x00\xb8\x00M\x00R\x01\x82\x00M\x00=\x00`\x00\x10\x01\xc2\x01\x95\x01\x9c\x00S\x00F\x01\xd7\x00~\x00\x08\x01j\x00\xcc\x01\xa8\x00\xbd\x00\x0f\x01\xb0\x01\xe1\x01\xe2\x00o\x01\r\x00_\x01%\x00\x97\x018\x00\xb8\x01\xc2\x00\xb0\x00\xcb\x002\x00`\x00\xca\x00\xe6\x01\xb2\x00v\x01P\x01\xde\x00s\x01w\x01X\x01\xaa\x01\x9e\x01\x19\x01\xc4\x00\xe2\x01u\x01\xfe\x01D\x01E\x00\'\x00|\x003\x01\xbc\x01\xc7\x00`\x00\xa7\x00D\x00\x1c\x01;\x00\xce\x004\x00\xd6\x006\x01#\x00\xa9\x01\xb3\x005\x01k\x01j\x00\x8d\x00\xfa\x00\x92\x01\x00\x01\xe1\x00\xfb\x00\x17\x00\x99\x00w\x00}\x00u\x01e\x01\x02\x00)\x01G\x00F\x01(\x01\xfd\x00\x03\x00\xcc\x00\xb3\x01\xce\x01U\x00~\x00\xe3\x00\t\x00\xbb\x00\x03\x01\xf1\x00]\x01\x81\x01 \x00\x12\x00\xee\x

In [90]:
import numpy as np
import reedsolo

# Initialize RS codec (4 redundant symbols per block, 2 correctable errors)
rs = reedsolo.RSCodec(4)  # Add 4 redundant symbols

# Example: Original indices
indices = np.random.randint(0, 512, size=(600,), dtype=np.uint16)  # Simulated indices
indices_bytes = indices.tobytes()  # Convert to bytes for RS encoding

# Encode with RS
encoded_data = rs.encode(indices_bytes)  # Add redundancy

# Save to a binary file
with open('encoded_data.bin', 'wb') as f:
    f.write(encoded_data)

print("Data encoded and saved to encoded_data.bin")

# Save to a binary file
with open('encoded_data_original.bin', 'wb') as f:
    f.write(indices_bytes)


Data encoded and saved to encoded_data.bin


In [77]:
# Load the binary file
with open('encoded_data.bin', 'rb') as f:
    received_data = f.read()

# Simulate noise (e.g., flip random bits)
def add_noise(data, num_errors):
    noisy_data = bytearray(data)
    for _ in range(num_errors):
        byte_index = np.random.randint(len(noisy_data))
        bit_index = np.random.randint(8)
        noisy_data[byte_index] ^= (1 << bit_index)  # Flip a random bit
    return bytes(noisy_data)

# Add noise to the data
noisy_data = add_noise(received_data, num_errors=10)  # Simulate 10 random bit errors

# Decode the noisy data
try:
    decoded_data = rs.decode(noisy_data)  # Correct errors
    if isinstance(decoded_data, tuple):  # Check if the result is a tuple
        decoded_data = decoded_data[0]  # Extract the actual decoded data
    decoded_indices = np.frombuffer(decoded_data, dtype=np.uint16)  # Convert back to integers
    print("Data decoded successfully!")
    print()
    print("Original Indices:", indices)
    print()
    print("Decoded Indices:", decoded_indices)
except reedsolo.ReedSolomonError as e:
    print(f"Error during decoding: {e}")




Error during decoding: Too many (or few) errors found by Chien Search for the errata locator polynomial!


In [94]:
import numpy as np
import reedsolo

# Initialize RS codec
r = 4  # Redundancy (4 symbols per block)
n = 255  # Total symbols per block
k = n - r  # Data symbols per block
rs = reedsolo.RSCodec(r)

# Simulated data
indices = np.random.randint(0, 512, size=(k * 2 + 3,), dtype=np.uint16)  # 2 blocks of data
indices_bytes = indices.tobytes()

# Encode the data
encoded_data = rs.encode(indices_bytes)

# Simulate noise (add random bit errors)
def add_noise(data, num_errors):
    noisy_data = bytearray(data)
    for _ in range(num_errors):
        byte_index = np.random.randint(len(noisy_data))
        bit_index = np.random.randint(8)
        noisy_data[byte_index] ^= (1 << bit_index)  # Flip a random bit
    return bytes(noisy_data)

noisy_data = add_noise(encoded_data, num_errors=20)  # Add errors across blocks

# Process data block by block
def decode_blocks(encoded_data, block_size, data_size, redundancy):
    decoded_result = bytearray()
    num_blocks = len(encoded_data) // block_size

    for i in range(num_blocks):
        start = i * block_size
        end = start + block_size
        block = encoded_data[start:end]

        try:
            # Attempt to decode the block
            decoded_block = rs.decode(block)
            if isinstance(decoded_block, tuple):  # Handle tuple output
                decoded_block = decoded_block[0]
            decoded_result.extend(decoded_block[:data_size])  # Append only data symbols
        except reedsolo.ReedSolomonError:
            # Decoding failed, append raw noisy data for this block
            print(f"Block {i + 1} could not be decoded. Retaining noisy data.")
            decoded_result.extend(block[:data_size])  # Append raw data symbols (exclude redundancy)

    return decoded_result

# Decode the noisy data
decoded_data = decode_blocks(noisy_data, block_size=n, data_size=k, redundancy=r)

# Convert the result back to integers
decoded_indices = np.frombuffer(decoded_data, dtype=np.uint16)

print("Decoded Indices (Best Effort):")
print(decoded_indices)

print("\nOriginal Indices:")
print(indices)


Block 1 could not be decoded. Retaining noisy data.
Decoded Indices (Best Effort):
[  394   286   196   283   160   363   510   456   223    72   136   207
    47   156   444   271   349     7   118   217   407   396  2530   355
   142   463   479   350    90   510   267   372   161   386   221   313
   366   488    69   429  8557   103   238    52   155   276   368    58
   359   339   271   452   505   359   129   318    15   387   271   129
   332    83   153   391   190   340    36   149   131   116   336   277
     2   333   301    75   306   332   463   277     2   480   213   111
   388   413    74    30   373   229   419   489    44   480   460    44
  4254   248   227   465   254   258   191  1165   425   178   173     0
   294   225   308   441    70   232   112   339   286   409   290   279
   179   159   249   260   342   438    58   224   140   506   501   111
    63   500   245    81   434    48    46   465   228   181   484   476
   459  1415   383   101    47   211   10

In [87]:
num_blocks = len(encoded_data) // n

num_blocks, len(encoded_data), n

(4, 1020, 255)

In [91]:
r = 4  # Redundancy (4 symbols per block)
n = 255  # Total symbols per block
k = n - r  # Data symbols per block
rs = reedsolo.RSCodec(r)

# Simulated data
indices = np.random.randint(0, 512, size=(k * 2 ,), dtype=np.uint16)  # 2 blocks of data
indices_bytes = indices.tobytes()

# Encode the data
encoded_data = rs.encode(indices_bytes)

with open('encoded_data.bin', 'wb') as f:
    f.write(encoded_data)

with open('encoded_data_original.bin', 'wb') as f:
    f.write(indices_bytes)

In [93]:
indices

array([244,  90, 133, 246, 349, 446, 179, 310, 200, 319,  75, 190, 256,
       423, 235, 456, 304, 398, 470,  99, 160,  67, 218, 218, 427, 497,
       410, 454,  60, 413, 238, 430,  96, 365, 481, 475, 278, 486, 437,
       400, 378, 400, 399,  78, 448, 439, 140, 379,   4, 205, 172, 436,
        88,  72, 174, 416, 494, 389,  61, 179,  96, 454, 413, 300, 164,
       104, 185, 203, 410, 435,  23,   2, 143, 143,  80, 363, 114, 446,
       270, 166, 462,  56, 502, 110, 274, 399, 250,  28, 259, 215, 282,
       474, 313, 160, 115, 201,  96, 168, 153, 285,  78,   1, 354, 253,
       284,  51, 299, 171, 179, 421, 210,  92, 394, 501, 178,  22, 396,
       242, 143, 387, 364, 503, 153, 344, 229,  70, 383, 330, 440, 139,
       303, 282, 392, 292, 254,  28,  90, 304, 260, 294, 399, 367, 461,
       137, 460, 364, 260, 479,  53, 360,   5,  37, 319, 362,  94, 135,
       163, 231, 300,  20, 180, 170,  28, 426, 343, 165,  71, 319, 453,
       114,  19, 105, 293, 302, 158, 504, 220,  25, 194, 277,  6